### PR TITLE
Make Mp3 smaller so it doesn't pass the TX buffer

### PR DESCRIPTION
**Pull request by kamijoutouma**

### CODE REVIEW

**Comment by MrColdbird** [comment]
Pass the TX buffer? Elaborate please on what the exact issue is... there should no longer be TX buffer related issues as the code contains overflow handlers afaik.

**Comment by kamijoutouma** [comment]
the server is always stalling at 0x0057C000 of 0x0062D31C bytes
the TX buffer stops clearing at that point

So i decided to make the file smaller then where the TX buffer stops. Hopefully that should fix the issue.

**Comment by kamijoutouma** [comment]
And it looks like that fixed it :3

**Comment by MrColdbird** [comment]
This is an issue with the server code rather than the file though and should be addressed in the code.
There has to be a reason as to why the TX buffer glitches out.

**Comment by NCDyson** [comment]
it's apparently anywhere after 5mb that it CAN stall and make the server unresponsive. Not sure if it happens on Touma's system, but running a local copy on my system and trying to access it from chrome, it locks up, but firefox loads just fine. It could very well be a browser issue.

**Comment by kamijoutouma** [comment]
Yeah i can give you and dyson a copy of the larger file for testing. But for now i think for compatibility reasons the live file should stay under 5MB.

I would also recommend rebuilding the live server with the new stuff again.

**Comment by NCDyson** [comment]
accessing the status page from my local server on my phone and clicking the title banner to get the music to play will also lock up the server until I refresh or leave the page

**Comment by kamijoutouma** [comment]
with the current file?

**Pull request merged**
